### ISSUE TITLE
Failing Test Cases.

### ISSUE THREAD

**Issue by samscott89** [rchatterjee/typtopcpp#2]
There are basically two types of failing test cases:
1. The DB logs are the incorrect length.
2. The `auth` check does not pass.

Presumably the first is caused by the URL not being available or something? You can easily make them pass by just purging the logs when `test == 1` or something.

For the second case, the `auth` function in `test_install` will never pass since you are attempting to authenticate a user different to the one you are acting as. There is a step which basically calls `/sbin/unix_chkpwd tmptyptop chkexpiry < /dev/null`, which will only ever succeed if the current uid is the same as the user `tmptyptop`. This is effectively the summary: http://jenkins-ci.361315.n4.nabble.com/Using-UNIX-PAM-authentication-from-a-non-root-user-tp378559p378563.html

If you run the tests with the same user as the test user it's fine.

**Comment by rchatterjee** [comment]
1. Fixed the server, so now the DB log upload tests are also passing. 
2. I changed the permission of `tests` script to the same as `su` and now seems like those tests are passing. 


Also, trying to fix the randomness to ensure that randomized tests show expected performance.

**Comment by rchatterjee** [comment]
Seems like we have the coveted bright green button from Travis.
